import {
  SignUpFormValues,
  LoginFormValues,
  Member,
  MembersApiResponse,
  Statement,
  ReportSummary,
  ReportTrend,
  TopUserReport,
} from "@/types/types";
import { Home, Users, DollarSign, FileText, Settings, LogOut } from "lucide-react";
import {} from "@/types/types";

import { MemberWithActions } from "@/pages/PeopleManagement/Members";
import { Column } from "@/types/types";
import { StatementWithActions } from "@/pages/Records/Statement";

export const SignUpInitialValues: SignUpFormValues = {
  name: "",
  email: "",
  address: "",
  password: "",
  confirmPassword: "",
  terms: false,
};

export const LoginInitialValues: LoginFormValues = {
  email: "",
  password: "",
};

export const dummyMembers: MemberWithActions[] = [
  {
    id: "101",
    _id: "1",
    firstName: "John",
    middleName: "Felix",
    surname: "Doe",
    email: "John@doe.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton", // no image → placeholder
  },
  {
    id: "102",
    _id: "2",
    firstName: "Smith",
    middleName: "UID-002",
    surname: "Rachael",
    email: "smith4@rachael.com",
    status: "Inactive",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "103",
    _id: "3",
    firstName: "Michael",
    middleName: "Spurs",
    surname: "Johnson",
    email: "mike@spirs.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "104",
    _id: "1",
    firstName: "John",
    middleName: "Felix",
    surname: "Doe",
    email: "John@doe.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton", // no image → placeholder
  },
  {
    id: "105",
    _id: "2",
    firstName: "Smith",
    middleName: "UID-002",
    surname: "Rachael",
    email: "smith4@rachael.com",
    status: "Inactive",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "106",
    _id: "3",
    firstName: "Michael",
    middleName: "Spurs",
    surname: "Johnson",
    email: "mike@spirs.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "107",
    _id: "1",
    firstName: "John",
    middleName: "Felix",
    surname: "Doe",
    email: "John@doe.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton", // no image → placeholder
  },
  {
    id: "108",
    _id: "2",
    firstName: "Smith",
    middleName: "UID-002",
    surname: "Rachael",
    email: "smith4@rachael.com",
    status: "Inactive",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "109",
    _id: "3",
    firstName: "Michael",
    middleName: "Spurs",
    surname: "Johnson",
    email: "mike@spirs.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "110",
    _id: "1",
    firstName: "John",
    middleName: "Felix",
    surname: "Doe",
    email: "John@doe.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton", // no image → placeholder
  },
  {
    id: "111",
    _id: "2",
    firstName: "Smith",
    middleName: "UID-002",
    surname: "Rachael",
    email: "smith4@rachael.com",
    status: "Inactive",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "112",
    _id: "3",
    firstName: "Michael",
    middleName: "Spurs",
    surname: "Johnson",
    email: "mike@spirs.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "113",
    _id: "1",
    firstName: "John",
    middleName: "Felix",
    surname: "Doe",
    email: "John@doe.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton", // no image → placeholder
  },
  {
    id: "114",
    _id: "2",
    firstName: "Smith",
    middleName: "UID-002",
    surname: "Rachael",
    email: "smith4@rachael.com",
    status: "Inactive",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "115",
    _id: "3",
    firstName: "Michael",
    middleName: "Spurs",
    surname: "Johnson",
    email: "mike@spirs.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "116",
    _id: "1",
    firstName: "John",
    middleName: "Felix",
    surname: "Doe",
    email: "John@doe.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton", // no image → placeholder
  },
  {
    id: "117",
    _id: "2",
    firstName: "Smith",
    middleName: "UID-002",
    surname: "Rachael",
    email: "smith4@rachael.com",
    status: "Inactive",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "118",
    _id: "3",
    firstName: "Michael",
    middleName: "Spurs",
    surname: "Johnson",
    email: "mike@spirs.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "119",
    _id: "1",
    firstName: "John",
    middleName: "Felix",
    surname: "Doe",
    email: "John@doe.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton", // no image → placeholder
  },
  {
    id: "120",
    _id: "2",
    firstName: "Smith",
    middleName: "UID-002",
    surname: "Rachael",
    email: "smith4@rachael.com",
    status: "Inactive",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "121",
    _id: "3",
    firstName: "Michael",
    middleName: "Spurs",
    surname: "Johnson",
    email: "mike@spirs.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "122",
    _id: "1",
    firstName: "John",
    middleName: "Felix",
    surname: "Doe",
    email: "John@doe.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton", // no image → placeholder
  },
  {
    id: "123",
    _id: "2",
    firstName: "Smith",
    middleName: "UID-002",
    surname: "Rachael",
    email: "smith4@rachael.com",
    status: "Inactive",
    role: "member",
    ActionButton: "ActionButton",
  },
  {
    id: "124",
    _id: "3",
    firstName: "Michael",
    middleName: "Spurs",
    surname: "Johnson",
    email: "mike@spirs.com",
    status: "Active",
    role: "member",
    ActionButton: "ActionButton",
  },
];

export const Dummy_Memebers_Column: Column<MemberWithActions>[] = [
  { id: "id", label: "ID", minWidth: 80 },
  { id: "firstName", label: "First Name", minWidth: 140 },
  { id: "middleName", label: "Middle Name", minWidth: 140 },
  { id: "surname", label: "Surname", minWidth: 120 },
  { id: "email", label: "Email", minWidth: 180 },
  // { id: "mobileNumber", label: "Mobile Number", minWidth: 140 },
  // { id: "address", label: "Address", minWidth: 160 },
  // { id: "residentialAddress", label: "Residential Address", minWidth: 180 },
  // { id: "stateOfOrigin", label: "State of Origin", minWidth: 140 },
  // { id: "LGA", label: "LGA", minWidth: 100 },
  // { id: "maritalStatus", label: "Marital Status", minWidth: 140 },
  // { id: "employer", label: "Employer", minWidth: 140 },
  // { id: "annualIncome", label: "Annual Income", minWidth: 140 },
  // { id: "monthlyContribution", label: "Monthly Contribution", minWidth: 180 },
  // { id: "nextOfKin", label: "Next of Kin", minWidth: 140 },
  // { id: "nextOfKinRelationship", label: "Next of Kin Relationship", minWidth: 180 },
  // { id: "nextOfKinAddress", label: "Next of Kin Address", minWidth: 180 },
  // { id: "dateOfBirth", label: "Date of Birth", minWidth: 140 },
  // { id: "createdAt", label: "Date Created", minWidth: 140 },
  // { id: "updatedAt", label: "Last Updated", minWidth: 140 },
  { id: "status", label: "Status", minWidth: 100 },
  { id: "role", label: "Role", minWidth: 100 },
  { id: "ActionButton", label: "Actions", align: "center", minWidth: 120 },
];

export const dummyStatements: StatementWithActions[] = [
  {
    id: "1",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Salary Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "2",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "ATM Withdrawal",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "3",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Fees Payment",
    type: "debit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "4",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "Pension Withdrawal",
    type: "credit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "5",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Ajo Contribution",
    type: "debit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "6",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "Laptop Purchase",
    type: "credit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "7",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Investment Payment",
    type: "debit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "8",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "Union Contribution",
    type: "credit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "9",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Ahlaja Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "10",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "Funds Withdrawal",
    type: "credit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "11",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Sharp Tv Purchase",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "12",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "Aina Fees",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "13",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Rent Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "14",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "ATShopM Withdrawal",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "15",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Ajo Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "16",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "Eforiro Purchase",
    type: "credit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "17",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Ahoe Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "18",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "Amazon Payment",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "19",
    name: "Amdnuel Essien",
    date: "2025-08-01T10:00:00Z",
    description: "Sandals Payment",
    type: "debit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "20",
    name: "Amdnuel Essien",
    date: "2025-08-02T12:00:00Z",
    description: "ATM Card Bills",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "21",
    name: "Folorunsho Abebi",
    date: "2025-08-01T10:00:00Z",
    description: "Shelve Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "22",
    name: "Folorunsho Abebi",
    date: "2025-08-02T12:00:00Z",
    description: "Lawma Payment",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "23",
    name: "Folorunsho Abebi",
    date: "2025-08-01T10:00:00Z",
    description: "Alfa Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "24",
    name: "Folorunsho Abebi",
    date: "2025-08-02T12:00:00Z",
    description: "Business Summit",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "25",
    name: "Folorunsho Abebi",
    date: "2025-08-01T10:00:00Z",
    description: "Nike Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "26",
    name: "Folorunsho Abebi",
    date: "2025-08-02T12:00:00Z",
    description: "Twenty Six",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "27",
    name: "Folorunsho Abebi",
    date: "2025-08-01T10:00:00Z",
    description: "Aloe Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "28",
    name: "Folorunsho Abebi",
    date: "2025-08-02T12:00:00Z",
    description: "Mineral Withdrawal",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "29",
    name: "Folorunsho Abebi",
    date: "2025-08-01T10:00:00Z",
    description: "Fine Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "30",
    name: "Folorunsho Abebi",
    date: "2025-08-02T12:00:00Z",
    description: "Plenary Withdrawal",
    type: "debit",
    amount: 1000,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  {
    id: "31",
    name: "Folorunsho Abebi",
    date: "2025-08-01T10:00:00Z",
    description: "Scholars Payment",
    type: "credit",
    amount: 5000,
    balance: 15000,
    ActionButton: "ActionButton",
  },
  {
    id: "32",
    name: "Folorunsho Abebi",
    date: "2025-08-02T12:00:00Z",
    description: "Film Withdrawal",
    type: "debit",
    amount: 100,
    balance: 14000,
    ActionButton: "ActionButton",
  },
  // ...add more records
];

export const Dummy_Statements_Column: Column<StatementWithActions>[] = [
  { id: "date", label: "Date", minWidth: 120, format: (v) => new Date(v).toLocaleDateString() },
  { id: "description", label: "Description", minWidth: 180 },
  { id: "type", label: "Type", minWidth: 80 },
  { id: "amount", label: "Amount", minWidth: 100, format: (v) => `₦${v.toLocaleString()}` },
  { id: "balance", label: "Balance", minWidth: 100, format: (v) => `₦${v.toLocaleString()}` },
  { id: "ActionButton", label: "Actions", align: "center", minWidth: 120 },
];

export const reportSummaries: ReportSummary[] = [
  { category: "transactions", total: 120000, count: 540, growth: 8 },
  { category: "loans", total: 80000, count: 120, growth: 5 },
  { category: "investments", total: 60000, count: 80, growth: 12 },
  { category: "withdrawals", total: 40000, count: 300, growth: -2 },
  { category: "savings", total: 90000, count: 200, growth: 10 },
];

// 5 categories × 6 days = 30 records
export const reportTrends: ReportTrend[] = [
  {
    category: "transactions",
    data: [
      { date: "2025-08-01", value: 10000 },
      { date: "2025-08-02", value: 12000 },
      { date: "2025-08-03", value: 9500 },
      { date: "2025-08-04", value: 14000 },
      { date: "2025-08-05", value: 11000 },
      { date: "2025-08-06", value: 12500 },
    ],
  },
  {
    category: "loans",
    data: [
      { date: "2025-08-01", value: 6000 },
      { date: "2025-08-02", value: 8500 },
      { date: "2025-08-03", value: 7200 },
      { date: "2025-08-04", value: 9000 },
      { date: "2025-08-05", value: 7800 },
      { date: "2025-08-06", value: 8200 },
    ],
  },
  {
    category: "investments",
    data: [
      { date: "2025-08-01", value: 7000 },
      { date: "2025-08-02", value: 7600 },
      { date: "2025-08-03", value: 6800 },
      { date: "2025-08-04", value: 8900 },
      { date: "2025-08-05", value: 7500 },
      { date: "2025-08-06", value: 8000 },
    ],
  },
  {
    category: "withdrawals",
    data: [
      { date: "2025-08-01", value: 4000 },
      { date: "2025-08-02", value: 3500 },
      { date: "2025-08-03", value: 4200 },
      { date: "2025-08-04", value: 3800 },
      { date: "2025-08-05", value: 4400 },
      { date: "2025-08-06", value: 3900 },
    ],
  },
  {
    category: "savings",
    data: [
      { date: "2025-08-01", value: 10000 },
      { date: "2025-08-02", value: 11000 },
      { date: "2025-08-03", value: 10800 },
      { date: "2025-08-04", value: 11500 },
      { date: "2025-08-05", value: 12000 },
      { date: "2025-08-06", value: 11800 },
    ],
  },
];

// 10 users across categories
export const topUsers: TopUserReport[] = [
  { id: "1", userId: "u1", name: "John Doe", amount: 20000, category: "investments", date: "2025-08-01" },
  { id: "2", userId: "u2", name: "Jane Smith", amount: 18000, category: "loans", date: "2025-08-01" },
  { id: "3", userId: "u3", name: "Samuel Green", amount: 15000, category: "transactions", date: "2025-08-02" },
  { id: "4", userId: "u4", name: "Grace Lee", amount: 17000, category: "savings", date: "2025-08-02" },
  { id: "5", userId: "u5", name: "Michael Brown", amount: 14500, category: "withdrawals", date: "2025-08-03" },
  { id: "6", userId: "u6", name: "Sophia Johnson", amount: 21000, category: "investments", date: "2025-08-03" },
  { id: "7", userId: "u7", name: "David Wilson", amount: 16000, category: "loans", date: "2025-08-04" },
  { id: "8", userId: "u8", name: "Emily Davis", amount: 15500, category: "transactions", date: "2025-08-04" },
  { id: "9", userId: "u9", name: "Daniel Garcia", amount: 19000, category: "savings", date: "2025-08-05" },
  { id: "10", userId: "u10", name: "Olivia Martinez", amount: 13500, category: "withdrawals", date: "2025-08-05" },
];

export const dummyLineData = [
  { date: "Jan", value: 400 },
  { date: "Feb", value: 300 },
  { date: "Mar", value: 500 },
  { date: "Apr", value: 280 },
  { date: "May", value: 590 },
  { date: "Jun", value: 390 },
  { date: "Jul", value: 490 },
  { date: "Aug", value: 600 },
  { date: "Sep", value: 510 },
  { date: "Oct", value: 420 },
  { date: "Nov", value: 580 },
  { date: "Dec", value: 450 },
];

export const dummyPieData = [
  { label: "Category A", value: 35 },
  { label: "Category B", value: 25 },
  { label: "Category C", value: 20 },
  { label: "Category D", value: 15 },
  { label: "Category E", value: 5 },
];
