import { SignUpFormValues, LoginFormValues, Member, MembersApiResponse } from "@/types/types";
import { Home, Users, DollarSign, FileText, Settings, LogOut } from "lucide-react";
import { MemberWithActions } from "@/pages/PeopleManagement/Members";
import { Column } from "@/types/types";

export const SignUpInitialValues: SignUpFormValues = {
  name: "",
  email: "",
  address: "",
  password: "",
  confirmPassword: "",
  terms: false,
};

export const LoginInitialValues: LoginFormValues = {
  email: "",
  password: "",
};

// export const dummyMembers: Member[] = [
//   {
//     _id: "1",
//     name: "John Doe",
//     uniqueId: "UID-001",
//     status: "Active",
//     address: "123 Main Street, Lagos",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "", // no image → placeholder
//   },
//   {
//     _id: "2",
//     name: "Jane Smith",
//     uniqueId: "UID-002",
//     status: "Inactive",
//     address: "45 Market Road, Abuja",
//     joinedAt: "2025-08-02",
//     contact: "+2348098765432",
//     image: "",
//   },
//   {
//     _id: "3",
//     name: "Michael Johnson",
//     uniqueId: "UID-003",
//     status: "Active",
//     address: "15 Ikoyi Crescent, Lagos",
//     joinedAt: "2025-08-05",
//     contact: "+2347012345678",
//     image: "",
//   },
//   {
//     _id: "4",
//     name: "John Doe",
//     uniqueId: "UID-001",
//     status: "Active",
//     address: "123 Main Street, Lagos",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "", // no image → placeholder
//   },
//   {
//     _id: "5",
//     name: "Jane Smith",
//     uniqueId: "UID-002",
//     status: "Inactive",
//     address: "45 Market Road, Abuja",
//     joinedAt: "2025-08-02",
//     contact: "+2348098765432",
//     image: "",
//   },
//   {
//     _id: "6",
//     name: "Michael Johnson",
//     uniqueId: "UID-003",
//     status: "Active",
//     address: "15 Ikoyi Crescent, Lagos",
//     joinedAt: "2025-08-05",
//     contact: "+2347012345678",
//     image: "",
//   },
//   {
//     _id: "7",
//     name: "John Doe",
//     uniqueId: "UID-001",
//     status: "Active",
//     address: "123 Main Street, Lagos",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "", // no image → placeholder
//   },
//   {
//     _id: "8",
//     name: "Jane Smith",
//     uniqueId: "UID-002",
//     status: "Inactive",
//     address: "45 Market Road, Abuja",
//     joinedAt: "2025-08-02",
//     contact: "+2348098765432",
//     image: "",
//   },
//   {
//     _id: "9",
//     name: "Michael Johnson",
//     uniqueId: "UID-003",
//     status: "Active",
//     address: "15 Ikoyi Crescent, Lagos",
//     joinedAt: "2025-08-05",
//     contact: "+2347012345678",
//     image: "",
//   },
//   {
//     _id: "10",
//     name: "John Doe",
//     uniqueId: "UID-001",
//     status: "Active",
//     address: "123 Main Street, Lagos",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "", // no image → placeholder
//   },
//   {
//     _id: "11",
//     name: "Jane Smith",
//     uniqueId: "UID-002",
//     status: "Inactive",
//     address: "45 Market Road, Abuja",
//     joinedAt: "2025-08-02",
//     contact: "+2348098765432",
//     image: "",
//   },
//   {
//     _id: "12",
//     name: "Michael Johnson",
//     uniqueId: "UID-003",
//     status: "Active",
//     address: "15 Ikoyi Crescent, Lagos",
//     joinedAt: "2025-08-05",
//     contact: "+2347012345678",
//     image: "",
//   },
//   {
//     _id: "13",
//     name: "John Doe",
//     uniqueId: "UID-001",
//     status: "Active",
//     address: "123 Main Street, Lagos",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "", // no image → placeholder
//   },
//   {
//     _id: "14",
//     name: "Jane Smith",
//     uniqueId: "UID-002",
//     status: "Inactive",
//     address: "45 Market Road, Abuja",
//     joinedAt: "2025-08-02",
//     contact: "+2348098765432",
//     image: "",
//   },
//   {
//     _id: "15",
//     name: "Michael Johnson",
//     uniqueId: "UID-003",
//     status: "Active",
//     address: "15 Ikoyi Crescent, Lagos",
//     joinedAt: "2025-08-05",
//     contact: "+2347012345678",
//     image: "",
//   },
//   {
//     _id: "16",
//     name: "John Doe",
//     uniqueId: "UID-001",
//     status: "Active",
//     address: "123 Main Street, Lagos",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "", // no image → placeholder
//   },
//   {
//     _id: "17",
//     name: "Jane Smith",
//     uniqueId: "UID-002",
//     status: "Inactive",
//     address: "45 Market Road, Abuja",
//     joinedAt: "2025-08-02",
//     contact: "+2348098765432",
//     image: "",
//   },
//   {
//     _id: "18",
//     name: "Michael Johnson",
//     uniqueId: "UID-003",
//     status: "Active",
//     address: "15 Ikoyi Crescent, Lagos",
//     joinedAt: "2025-08-05",
//     contact: "+2347012345678",
//     image: "",
//   },
// ];

// export const Dummy_Memebers_Column: Member[] = [
//   {
//     id: "id",
//     name: "Faraday Michael",
//     uniqueId: "478666dhgs762ugyd",
//     status: "Active",
//     address: "43, komolafe Junction, Middle Estate",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "",
//   },
//   {
//     id: "name",
//     name: "Michael Aderinsola",
//     uniqueId: "478666dhgs762ugyd",
//     status: "Active",
//     address: "43, komolafe Junction, Middle Estate",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "",
//   },
//   {
//     id: "uniqueId",
//     name: "Stineil Henry",
//     uniqueId: "478666dhgs762ugyd",
//     status: "Active",
//     address: "43, komolafe Junction, Middle Estate",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "",
//   },
//   {
//     id: "status",
//     name: "Chukwu Kenbene",
//     uniqueId: "478666dhgs762ugyd",
//     status: "Active",
//     address: "43, komolafe Junction, Middle Estate",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "",
//   },
//   {
//     id: "address",
//     name: "Ben Edwards",
//     uniqueId: "478666dhgs762ugyd",
//     status: "Active",
//     address: "43, komolafe Junction, Middle Estate",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "",
//   },
//   {
//     id: "dateJoined",
//     name: "Rita Domnic",
//     uniqueId: "478666dhgs762ugyd",
//     status: "Active",
//     address: "43, komolafe Junction, Middle Estate",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "",
//   },
//   {
//     id: "contactNumber",
//     name: "Steward Isreal",
//     uniqueId: "478666dhgs762ugyd",
//     status: "Active",
//     address: "43, komolafe Junction, Middle Estate",
//     joinedAt: "2025-08-01",
//     contact: "+2348012345678",
//     image: "",
//   },
// ];

export const Dummy_Memebers_Column: Column<MemberWithActions>[] = [
  { id: "id", label: "ID", minWidth: 80 },
  { id: "firstName", label: "First Name", minWidth: 140 },
  { id: "middleName", label: "Middle Name", minWidth: 140 },
  { id: "surname", label: "Surname", minWidth: 120 },
  { id: "email", label: "Email", minWidth: 180 },
  // { id: "mobileNumber", label: "Mobile Number", minWidth: 140 },
  // { id: "address", label: "Address", minWidth: 160 },
  // { id: "residentialAddress", label: "Residential Address", minWidth: 180 },
  // { id: "stateOfOrigin", label: "State of Origin", minWidth: 140 },
  // { id: "LGA", label: "LGA", minWidth: 100 },
  // { id: "maritalStatus", label: "Marital Status", minWidth: 140 },
  // { id: "employer", label: "Employer", minWidth: 140 },
  // { id: "annualIncome", label: "Annual Income", minWidth: 140 },
  // { id: "monthlyContribution", label: "Monthly Contribution", minWidth: 180 },
  // { id: "nextOfKin", label: "Next of Kin", minWidth: 140 },
  // { id: "nextOfKinRelationship", label: "Next of Kin Relationship", minWidth: 180 },
  // { id: "nextOfKinAddress", label: "Next of Kin Address", minWidth: 180 },
  // { id: "dateOfBirth", label: "Date of Birth", minWidth: 140 },
  // { id: "createdAt", label: "Date Created", minWidth: 140 },
  // { id: "updatedAt", label: "Last Updated", minWidth: 140 },
  { id: "status", label: "Status", minWidth: 100 },
  { id: "role", label: "Role", minWidth: 100 },
  { id: "ActionButton", label: "Actions", align: "center", minWidth: 120 },
];
